import { Inter } from "next/font/google";
import "./globals.css";
import HeaderComponent from "./ui/full-components/HeaderComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="z-10 w-full justify-between font-mono text-sm h-screen">
        <nav className="fixed max-w-5xl  left-0 top-0 flex w-full justify-around border-b border-gray-300 color-change-2x from-zinc-200 pb-6 pt-8 backdrop-blur-2xl dark:border-neutral-800 dark:from-inherit lg:static lg:rounded-xl lg:border lg:p-4">
          <HeaderComponent/>
        </nav>
        {children}
         
      </div>
      </body>
    </html>
  );
}
